#!/usr/bin/env python

from __future__ import absolute_import
from multiprocessing import Lock
import optparse
import sys

from reposync.fs_monitor import *

if __name__ == '__main__':
  parser = optparse.OptionParser()
  parser.add_option('-r', '--repo', action="store", dest="repos", help="Repository roots to monitor")
  parser.add_option('-b', '--branch', action="store", dest="branch",
          default="integration", help="Which branch should be pushed")
  parser.add_option('-v', '--verbose', action="store_true", dest="verbose", default=False, help="More output")
  parser.add_option('-V', '--wicked-verbose', action='store_true', dest="wicked_verbose", default=False, help="Wicked more output")
  options, remainder = parser.parse_args()
  if options.repos is None:
    print("You must specify at least one repository to monitor")
    sys.exit(1)
  log_level = logging.WARNING
  if options.verbose and options.wicked_verbose:
    print('Dude, do you want more output or wicked more output (Please use either -v or -V, not both)')
    sys.exit(1)
  if options.verbose:
    log_level = logging.INFO
  if options.wicked_verbose:
    log_level = logging.DEBUG
  logging.basicConfig(level=log_level, format="%(levelname)s - %(asctime)s (%(name)s:%(funcName)s):  %(msg)s")
  mutex = Lock()
  monitor = FileSystemMonitor(mutex, options.branch, options.repos.split(','))
  monitor.start()
