#!/usr/bin/env python

from __future__ import absolute_import

import optparse

from reposync.fs_monitor import *

if __name__ == '__main__':
  parser = optparse.OptionParser()
  parser.add_option('-r', '--repos', action="store", destination="repos", help="Repository roots to monitor")
  parser.add_option('-v', '--verbose', action="store_true", dest="verbose", default=False, help="More output")
  parser.add_option('-V', '--wicked-verbose', action='store_true', dest="wicked_verbose", default=False, help="Wicked more output")
  options, remainder = parser.parse_args()
  log_level = logging.WARNING
  if options.verbose and options.wicked_verbose:
    print('Dude, do you want more output or wicked more output (Please use either -v or -V, not both)')
    sys.exit(1)
  if options.verbose:
    log_level = logging.INFO
  if options.wicked_verbose:
    log_level = logging.DEBUG
  logging.basicConfig(level=log_level, format="%(levelname)s - %(asctime)s (%(name)s:%(funcName)s):  %(msg)s")
  monitor = FileSystemMonitor('/tmp/foo')
  monitor.start()
